name: Python CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * *'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.10.4'
            architecture: 'x64'
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: python -m pip install "pandas==1.4.2" "requests==2.27.1" "lxml==4.8.0"
      - name: Fetch data
        run: python download_script.py
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/
          if-no-files-found: error
      - name: See where we are
        shell: bash
        run: |
          pwd
          ls -lah
      - name: Set up the SSH key and the known_hosts file
        shell: bash
        run: |
          echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
      - name: Configure git
        shell: bash
        run: |
          mkdir -p ~/workdir
          cd workdir
          git config --global user.email "no-reply@github.com"
          git config --global user.name "ci-build@github.com"
          git clone --depth 1 git@github.com:TheSnoozer/putcallratio.git
          cd putcallratio
          git checkout data
          TODAY=$(date "+%Y-%m-%d")
          cp build/total_options.html ${TODAY}_datatotal.html
          cp build/index_options.html ${TODAY}_dataindex.html
          cp build/equity_options.html ${TODAY}_dataequity.html
          git add ${TODAY}_datatotal.html ${TODAY}_dataindex.html ${TODAY}_dataequity.html
          git commit -m "Add data for ${TODAY}"
          git push -o ci.skip -q git@github.com:TheSnoozer/putcallratio.git data
