name: Python CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 23 * * *'

jobs:
  fetch-data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
            python-version: '3.10.4'
            architecture: 'x64'
      - name: Display Python version
        run: python --version
      - name: Install dependencies
        run: python -m pip install "pandas==1.4.2" "requests==2.27.1" "lxml==4.8.0"
      - name: Fetch data
        run: python download_script.py
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/
          if-no-files-found: error

